language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
script: gradle shadowJar
notifications:
  webhooks: https://discordapp.com/api/webhooks/309346635400478720/YivaaAYBaRj2U3QWu-Iqyvj60ib0a4Xk0EpRC-ulvc4OM4QfVMCt1gma4lVtrnxmJg_X
